- id: search-and-replace
  name: Search and replace strings
  description: Search and replace strings
  entry: bin/search-and-replace.rb
  language: script
  pass_filenames: true
  exclude_types:
    - binary
